urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic import list_detail, date_based
from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import FlatPageSitemap

from plumbaker.apps.availability.models import Location
from plumbaker.apps.inventory.models import Good, Portion, Type
from plumbaker.apps.ingredients.models import Ingredient
from plumbaker.apps.media.models import Photo
from plumbaker.apps.press.models import Mention, Release
from plumbaker.apps.category.models import Category
from plumbaker.feeds import LatestNewsFeed
from plumbaker.sitemaps import NewsSitemap, GoodsSitemap
from plumbaker.robots import robots_txt

admin.autodiscover()

# Category dicts
category_list_info_dict = {
	'queryset': Category.objects.all(),
	'allow_empty': True,
}

category_detail_info_dict = {
	'queryset': Category.objects.all(),
#	'extra_context' : {'release_list': get_live_releases},
	'template_object_name': 'category',
}

# Ingredient dicts
ingredient_list_info_dict = {
	'queryset': Ingredient.objects.all(),
	'allow_empty': True,
}

ingredient_detail_info_dict = {
	'queryset': Ingredient.objects.all(),
	'template_object_name': 'ingredient',
}

# Baked-good dicts
inventory_list_info_dict = {
	'queryset': Good.objects.all(),
	'allow_empty': True,
}

inventory_detail_info_dict = {
	'queryset': Good.objects.all(),
	'template_object_name': 'good',
}

# Location dicts
location_list_info_dict = {
	'queryset': Location.current.all(),
	'allow_empty': True,
}

location_detail_info_dict = {
	'queryset': Location.objects.all(),
	'template_object_name': 'location',
}

# Baked good types dicts
type_list_info_dict = {
	'queryset': Type.objects.all(),
	'allow_empty': True,
}

type_detail_info_dict = {
	'queryset': Type.objects.all(),
	'template_object_name': 'type',
}

# News dict
news_info_dict = {
	'queryset': Release.live.all(),
	'date_field': 'pub_date',
	'template_object_name': 'release',
}

news_list_info_dict = {
	'queryset': Release.live.all().order_by('-pub_date'),
	'paginate_by': 15,
}

# Mention dict
mention_list_info_dict = {
	'queryset': Mention.objects.all(),
	'allow_empty': True,
	'template_object_name': 'mention',
}

# Feeds
feeds = {
	'news': LatestNewsFeed,
}

# Sitemaps
sitemaps = {
	'news': NewsSitemap,
	'goods': GoodsSitemap,
    'flatpages': FlatPageSitemap,
}


urlpatterns = patterns('',
	# Robots
	(r'^robots.txt$', robots_txt),

	# Home page
	(r'^$', 'django.views.generic.simple.direct_to_template', {'template': 'home.html'}),
	#(r'^$', 'patrickbeeson.views.home_page'),

	# Baked goods
	(r'^baked-goods/$', list_detail.object_list, inventory_list_info_dict),
	(r'^baked-goods/(?P<slug>[-\w]+)/$', list_detail.object_detail, inventory_detail_info_dict),

	# Baked good types
	(r'^baked-good-types/$', list_detail.object_list, type_list_info_dict),
	(r'^baked-good-types/(?P<slug>[-\w]+)/$', list_detail.object_detail, type_detail_info_dict),

	# Ingredients
	(r'^ingredients/$', list_detail.object_list, ingredient_list_info_dict),
	(r'^ingredients/(?P<slug>[-\w]+)/$', list_detail.object_detail, ingredient_detail_info_dict),

	# Category
	(r'^categories/$', list_detail.object_list, category_list_info_dict),
	(r'^categories/(?P<slug>[-\w]+)/$', list_detail.object_detail, category_detail_info_dict),

	# Locations
	(r'^locations/$', list_detail.object_list, location_list_info_dict),
	(r'^locations/(?P<slug>[-\w]+)/$', list_detail.object_detail, location_detail_info_dict),

	# News
	(r'^press/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\w-]+)/$', date_based.object_detail, dict(news_info_dict, slug_field='slug')),
	(r'^press/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$', date_based.archive_day, news_info_dict),
	(r'^press/(?P<year>\d{4})/(?P<month>[a-z]{3})/$', date_based.archive_month, news_info_dict),
	(r'^press/(?P<year>\d{4})/$', date_based.archive_year, dict(news_info_dict, make_object_list=True)),
	(r'^press/$', list_detail.object_list, news_list_info_dict),
	(r'^press/mentions/$', list_detail.object_list, mention_list_info_dict),

	# Contact form
	(r'^contact/', include('contact_form.urls')),
	
	# Feeds
	(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', { 'feed_dict': feeds }),
	
	# Sitemaps
	(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
	(r'^sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

	(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^admin/', include(admin.site.urls)),
	
	# Flatpages
	(r'', include('django.contrib.flatpages.urls')),

)

apps/inventory/models.py
from django.db import models
from markdown import markdown
from plumbaker.apps.ingredients.models import Ingredient
from plumbaker.apps.availability.models import Location
from plumbaker.apps.media.models import Photo

class Good(models.Model):
	name = models.CharField(max_length=50)
	slug = models.SlugField(help_text='This field will prepopulate from the name field.', unique=True)
	description = models.TextField(help_text='A brief summary of this baked good. Use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.')
	description_html = models.TextField(editable=False, blank=True)
	good_type = models.ForeignKey('Type')
	ingredients = models.ManyToManyField(Ingredient)
	lead_photo = models.ForeignKey(Photo, null=True, blank=True, help_text='Photo will be resized on the template.')
	where_to_buy = models.ManyToManyField(Location, blank=True)
	is_seasonal = models.BooleanField(default=False)
	is_available = models.BooleanField(default=True)
	keywords = models.CharField(max_length=200, blank=True, help_text='Enter a comma-separated list of keywords.')
	google_checkout_html = models.TextField(blank=True)
	google_checkout_javascript = models.TextField(blank=True)

	class Meta:
		verbose_name_plural = 'goods'
		
	def __unicode__(self):
		return self.name

	def save(self):
		self.description_html = markdown(self.description)
		super(Good, self).save()
	
	def get_absolute_url(self):
		return '/baked-goods/%s/' % (self.slug)

class Portion(models.Model):
	PORTION_TYPES = (
		(u'S', u'Small'),
		(u'M', u'Medium'),
		(u'L', u'Large'),
		(u'PL', u'Petite loaf'),
		(u'FL', u'Full loaf'),
	)
	portion_type = models.CharField(max_length=2, choices=PORTION_TYPES)
	quantity = models.PositiveIntegerField()
	baked_good = models.ForeignKey(Good)
	cost = models.DecimalField(max_digits=5, decimal_places=2)
	nutritional_information = models.TextField(blank=True, help_text='The nutritional information for this portion size. Use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.')
	nutritional_information_html = models.TextField(editable=False, blank=True)
	notes = models.TextField(help_text='Add any notes for this portion here. This will not be shown to the public.', blank=True)

	def save(self):
		self.nutritional_information_html = markdown(self.nutritional_information)
		super(Portion, self).save()

class Type(models.Model):
	title = models.CharField(max_length=50)
	slug = models.SlugField(help_text='This field will prepopulate from the title field.', unique=True)
	description = models.TextField(help_text='A brief description of this baked good type. Use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>.')
	description_html = models.TextField(editable=False, blank=True)
	keywords = models.CharField(max_length=200, help_text='Comma-separated keywords describing the type. Limit 200 characters.', blank=True)
		
	class Meta:
		verbose_name_plural = 'types'
		
	def __unicode__(self):
		return self.title

	def save(self):
		self.description_html = markdown(self.description)
		super(Type, self).save()
	
	def get_absolute_url(self):
		return '/baked-good-types/%s/' % (self.slug)

templates/inventory/good_detail.html
{% extends "base_inventory.html" %}

{% load humanize images cache %}

{% block title %}{{ good.name }} {{ block.super }}{% endblock %}

{% block meta_description %}{{ good.description_html|striptags }}{% endblock %}

{% block meta_keywords %}{% if good.keywords %}{{ good.keywords }}{% endif %}{% endblock %}

{% block facebook_meta_data %}
<meta property="og:title" content="{{ good.name }}"/>
<meta property="og:site_name" content="theplumbaker.com"/>
{% if good.lead_photo %}<meta property="og:image" content="{{ good.lead_photo.photo|thumbnail:"520x500" }}"/>{% endif %}
<meta property="og:type" content="food" />
<meta property="og:url" content="http://theplumbaker.com{{ good.get_absolute_url }}"/>
<meta property="og:description" content="{{ good.description_html|striptags }}"/>
<meta property="fb:admins" content="500460979, 27403640"/>
<meta property="og:email" content="lindsay@theplumbaker.com"/>
<meta property="fb:app_id" content="122417281126639" />
{% endblock %}

{% block content_level %}detail{% endblock %}

{% block main_content %}
	{% if not good.is_available %}<p class="alert">This baked good is not available currently.</p>{% endif %}

	<h2>{{ good.name }} {% if good.is_seasonal %}<span id="seasonal">(Seasonal)</span>{% endif %}</h2>

	{% if good.lead_photo %}
	<div id="lead_photo">
		<img src="{{ good.lead_photo.photo|thumbnail:"520x500" }}" alt="{{ good.lead_photo.caption }}">
		<p class="photo_credit">Photo by: {% if good.lead_photo.credit_link %}<a href="{{ good.lead_photo.credit_link }}" title="{{ good.lead_photo.credit }}'s Web site">{{ good.lead_photo.credit }}</a>{% else %}{{ good.lead_photo.credit }}{% endif %}</p>
		<p class="photo_caption">{{ good.lead_photo.caption_html|safe }}</p>
	</div>
	{% endif %}

	{{ good.description_html|safe }}
	
	{% if good.google_checkout_html %}{{ good.google_checkout_html|safe }}{% endif %}
	
	<h3>Ingredients</h3>
	
	<p>The {{ good.ingredients.count|apnumber }} ingredient{{ good.ingredients.count|pluralize }} for the {{ good.name }} include:
	{% cache 500 ingredients_in_good good.id %}
	{% for ingredient in good.ingredients.all %}
	<a href="{{ ingredient.get_absolute_url }}" title="{{ ingredient.description }}">{{ ingredient.name }}</a>
	{% if forloop.last %}{% else %}
	{% ifequal forloop.revcounter0 1 %}and {% else %},{% endifequal %}
	{% endif %}
	{% endfor %}
	{% endcache %}.
	</p>
	
	<p class="note"><em>Note: Baked goods may include additional ingredients such as salt or baking powder not listed here.</em></p>
	
	{% if good.portion_set.all %}
	<h3>Sizes and nutritional information</h3>
	
	<dl id="good_detail_list">
	{% cache 500 portions_for_good good.id %}
	{% for good in good.portion_set.all %}
		<dt class="size">Portion size: {{ good.get_portion_type_display }}</dt>
		<dd class="quantity">Quantity: {% ifequal good.quantity 12 %}Dozen{% else %}{{ good.quantity }}{% endifequal %}</dd>
		{% if good.nutritional_information %}<dd class="nutrition details">Nutrition details: {{ good.nutritional_information_html|safe }}</dd>{% endif %}
		<dd class="cost">Cost: ${{ good.cost }}</dd>
	{% endfor %}
	{% endcache %}	
	</dl>
	{% endif %}
	
	<fb:like show_faces="false" width="520" font="helvetica" autologoutlink="true"></fb:like>
{% endblock %}

{% block utility_links %}
	<h2>Where you can buy this item</h2>
	{% if good.where_to_buy.count %}
	<ul class="utility_item_list">
	{% cache 500 good_location_list good.id %}
	{% for location in good.where_to_buy.all %}
	{% ifequal location.is_current_vendor 1 %}
		<li><a href="{{ location.get_absolute_url }}" title="{{ location.description }}">{{ location.name }}</a></li>
	{% endifequal %}
	{% endfor %}
	{% endcache %}
	</ul>
	{% else %}<ul class="utility_item_list"><li>By request only</li></ul>{% endif %}
	
	<h2>Related baked goods</h2>
	
	<ul class="utility_item_list">
	{% cache 500 related_good_list good.id %}
	{% for good in good.good_type.good_set.all %}
		<li><a href="{{ good.get_absolute_url }}" title="{{ good.description }}">{{ good.name }}</a></li>
	{% endfor %}
	{% endcache %}
	</ul>
	
{% endblock %}

{% block google_checkout_javascript %}{% if good.google_checkout_javascript %}{{ good.google_checkout_javascript|safe }}{% endif %}{% endblock %}
{% block facebook_js_sdk %}
<div id="fb-root"></div>
    <script>
      window.fbAsyncInit = function() {
        FB.init({appId: '122417281126639', status: true, cookie: true,
                 xfbml: true});
      };
      (function() {
        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.src = document.location.protocol +
          '//connect.facebook.net/en_US/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
      }());
    </script>
{% endblock %}

templates/inventory/good_list.html
{% extends "base_inventory.html" %}

{% load cache types %}

{% block title %}Baked goods {{ block.super }}{% endblock %}

{% block content_level %}list{% endblock %}

{% block main_content %}
<h2>Baked goods</h2>

<p>The Plum Baker sells the following baked goods:</p>
{% cache 500 goodlist %}
{% regroup object_list|dictsort:"good_type.title" by good_type as type_list %}
<ul id="content_list">
	{% for good_type in type_list %}
	<li class="content_list_header"><strong>{{ good_type.grouper }}</strong></li>
		<ul>
		{% for object in good_type.list %}
			<li><a href="{{ object.get_absolute_url }}" title="{{ object.name }}">{{ object.name }}</a></li>
		{% endfor %}
		</ul>
	{% endfor %}
</ul>
{% endcache %}

{% comment %}
<ul id="content_list">
{% cache 500 good_list %}
{% for object in object_list %}
	<li><a href="{{ object.get_absolute_url }}" title="{{ object.description }}">{{ object.name }}</a></li>
{% endfor %}
{% endcache %}
</ul>
{% endcomment %}
{% endblock %}

{% block utility_links %}
<h2>Baked-good types</h2>

<ul class="utility_item_list">
{% cache 500 goodtype_list %}
{% get_goodtypes_list as type_list %}
{% for type in type_list %}
	<li><a href="{{ type.get_absolute_url }}" title="{{ type.title }}">{{ type.title }}</a></li>
{% endfor %}
{% endcache %}
</ul>

{% endblock %}

templates/inventory/type_detail.html
{% extends "base_inventory.html" %}

{% load humanize cache %}

{% block title %}{{ type.title }} {{ block.super }}{% endblock %}

{% block meta_description %}{% if type.description %}{{ type.description }}{% endif %}{% endblock %}

{% block meta_keywords %}{% if type.keywords %}{{ type.keywords }}{% endif %}{% endblock %}

{% block content_level %}detail{% endblock %}

{% block main_content %}
	<h2>{{ type.title }}</h2>

	{{ type.description_html|safe }}

{% endblock %}

{% block utility_links %}
<h2>Baked goods for this type</h2>

<ul class="utility_item_list">
{% cache 500 good_type_list type.title %}
{% for good in type.good_set.all %}
	<li><a href="{{ good.get_absolute_url }}" title="{{ good.description }}">{{ good.name }}</a></li>
{% endfor %}
{% endcache %}
</ul>

{% endblock %}

templates/inventory/type_list.html
{% extends "base_inventory.html" %}

{% load cache %}

{% block title %}Baked good types {{ block.super }}{% endblock %}

{% block content_level %}list{% endblock %}

{% block meta_description %}A list of baked good types from The Plum Baker.{% endblock %}

{% block meta_keywords %}baked good types, cookies, cakes, baking, Knoxville, Tennessee{% endblock %}

{% block main_content %}
	<h2>Baked good types</h2>

	<p>The Plum Baker sells <a href="/baked-goods/">baked goods</a> of the following types:</p>

	<ul id="content_list">
	{% cache 500 good_type_list %}
	{% for object in object_list %}
		<li><a href="{{ object.get_absolute_url }}" title="{{ object.title }}">{{ object.title }}</a></li>
	{% endfor %}
	{% endcache %}
	</ul>
{% endblock %}

{% block utility_links %}{% endblock %}